requires root instead of sudo now; removed inclusion of the optional icon; moves the package to the source directory so it's easy to find

diff --git a/create_deb b/create_deb
--- a/create_deb
+++ b/create_deb
@@ -1,27 +1,38 @@
 #!/bin/bash
 
+RED="\033[1;31m"
+NOCOLOR="\033[0m"
+
+if [ "$(whoami)" != "root" ]; then
+	echo -e "${RED}Error:$NOCOLOR Needs root permission"
+	exit 1
+fi
+
 VERSION=${VERSION:-0.9.6}
-REVISION=2
-SRCDIR=${SRCDIR:-"."}
+REVISION=3
+SRCDIR=${SRCDIR:-"$(pwd)"}
 TMPDIR="/tmp/aletheia_${VERSION}-${REVISION}_all"
 
 if [ -e "$TMPDIR" ]; then
-	sudo rm -rf "$TMPDIR"
+	rm -rf "$TMPDIR"
 fi
 
 mkdir -p "$TMPDIR"/DEBIAN "$TMPDIR"/usr/bin "$TMPDIR"/usr/share/man/man1/ "$TMPDIR"/usr/share/icons/
-
-#cp "$SRCDIR/aletheia" "$TMPDIR"
-#cp "$SRCDIR/aletheia.1" "$TMPDIR"
 
 echo -e "Package: aletheia\nVersion: ${VERSION}\nArchitecture: all\nMaintainer: Brad Hermanson <apeitheo@gmail.com>\nDepends: pulseaudio-utils, calc, bc, gtts, espeak-ng, sox, ffmpeg, mplayer\nDescription: A CLI media player with pitch controls and voice feedback." >"$TMPDIR"/DEBIAN/control
 
 cp "$SRCDIR/aletheia" "$TMPDIR/usr/bin/"
 cp "$SRCDIR/aletheia.1" "$TMPDIR/usr/share/man/man1/"
-cp "$SRCDIR/aletheia.png" "$TMPDIR/usr/share/icons/"
 
 chmod 755 "$TMPDIR/usr/bin/aletheia"
 chmod 644 "$TMPDIR/usr/share/man/man1/aletheia.1"
 cd "$TMPDIR"
-sudo chown -R root:root "$TMPDIR"
-sudo dpkg-deb --build "$TMPDIR"
+chown -R root:root "$TMPDIR"
+dpkg-deb --build "$TMPDIR"
+if [ -e "/tmp/aletheia_${VERSION}-${REVISION}_all.deb" ]; then
+	mv /tmp/aletheia_${VERSION}-${REVISION}_all.deb $SRCDIR
+	echo "Moved aletheia_${VERSION}-${REVISION}_all.deb to $SRCDIR"
+else
+	echo -e "${RED}Error:$NOCOLOR Package does not exist"
+	exit 1
+fi
