require running as root instead of utilizing sudo as that was causing issues and is not set up on everyone's machine; ensure permissions are correct; cleanup

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,116 +8,66 @@ RED="\033[1;31m"
 
 DESTDIR=${DESTDIR:-/usr/local}
 
-quit=false
+QUIT=false
+USER="$(whoami)"
 
 echo -ne "${GREEN}Aletheia `cat aletheia | grep \"VERSION=\" | cut -d'\"' -f2`\n\n"
 echo -ne "${BLUE}Checking for dependencies...\n\n"
 
-echo -ne "${NOCOLOR}checking for pactl... "
-if [ "`which pactl 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
+check_dep() {
+	local dependency_name="$1"
 
-echo -ne "${NOCOLOR}checking for calc... "
-if [ "`which calc 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
+	echo -ne "${NOCOLOR}checking for $dependency_name... "
 
-echo -ne "${NOCOLOR}checking for bc... "
-if [ "`which bc 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
+	if [ "$(which "$dependency_name" 2>/dev/null)" == "" ]; then
+		echo -e "${RED}no"
+		QUIT=true
+	else
+		echo -e "${GREEN}yes"
+	fi
+}
 
-echo -ne "${NOCOLOR}checking for gtts-cli... "
-if [ "`which gtts-cli 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
+check_dep pactl
+check_dep calc
+check_dep bc
+check_dep gtts-cli
+check_dep play
+check_dep espeak-ng
+check_dep sox
+check_dep ffprobe
+check_dep ffmpeg
+check_dep iconv
+check_dep mplayer
 
-echo -ne "${NOCOLOR}checking for play... "
-if [ "`which play 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
-
-echo -ne "${NOCOLOR}checking for espeak-ng... "
-if [ "`which espeak-ng 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
-
-echo -ne "${NOCOLOR}checking for sox... "
-if [ "`which sox 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
-
-echo -ne "${NOCOLOR}checking for ffmpeg... "
-if [ "`which ffmpeg 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
-
-echo -ne "${NOCOLOR}checking for ffprobe... "
-if [ "`which ffprobe 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
-
-echo -ne "${NOCOLOR}checking for mplayer... "
-if [ "`which mplayer 2>/dev/null`" == "" ]; then
-	echo -e "${RED}no"
-	quit=true
-else
-	echo -e "${GREEN}yes"
-fi
-
-if [ "$quit" == true ]; then
+if [ "$QUIT" == true ]; then
 	echo -ne "\n${RED}Error: Unresolved dependencies$NOCOLOR\n"
 	exit 1
 fi
 
 if [ ! -w "$DESTDIR" ]; then
-	echo -ne "\n${BLUE}Sudo password required to install in $DESTDIR\n\n$NOCOLOR"
+	echo -e "\n${RED}Error:$NOCOLOR Need root permission to install in $DESTDIR"
+	exit 1
 fi
 
-sudo mkdir -p "$DESTDIR/bin/"
-sudo mkdir -p "$DESTDIR/share/man/man1/"
-sudo install -m 755 aletheia "$DESTDIR/bin/"
-sudo install -m 644 aletheia.1 "$DESTDIR/share/man/man1/"
-sudo chown root:root "$DESTDIR/bin/aletheia"
-sudo chown root:root "$DESTDIR/share/man/man1/aletheia.1"
-sudo mandb
-echo ""
-echo -e "${GREEN}Aletheia successfully installed in:$NOCOLOR"
-echo ""
+mkdir -p "$DESTDIR/bin/"
+mkdir -p "$DESTDIR/share/man/man1/"
+
+install -m 755 aletheia "$DESTDIR/bin/"
+install -m 644 aletheia.1 "$DESTDIR/share/man/man1/"
+
+chown "$USER:$USER" "$DESTDIR/bin/aletheia"
+chown "$USER:$USER" "$DESTDIR/share/man/man1/aletheia.1"
+
+mandb >/dev/null 2>/dev/null
+
+echo -e "\n${GREEN}Aletheia successfully installed in:$NOCOLOR\n"
 echo "${DESTDIR}/bin/aletheia"
-echo "${DESTDIR}/share/man/man1/aletheia.1"
-echo ""
+echo -e "${DESTDIR}/share/man/man1/aletheia.1\n"
+
 if [ "$DESTDIR" != "/usr/local" ] || [ "$DESTDIR" != "/usr/local/" ]; then
 	echo -e "${GREEN}Use DESTDIR=${DESTDIR} ./uninstall to remove$NOCOLOR"
 else
 	echo -e "${GREEN}Use ./uninstall to remove$NOCOLOR"
 fi
-echo ""
+
+echo
