- Added support for translations. I generated translations for ~30 languages using AI, but am not uploading them to GitHub at this time until they're verified. I am considering uploading them as a zip file on my Patreon as an optional download until then. - Fixed a long-standing bug that caused Aletheia to become somewhat unresponsive after a while, especially when paused. - New LANGUAGE config option with 'en' as the default. Takes a two-letter country code. Requires the corresponding translation files which are not available yet. - Ctrl-v on the setup screen can now swap between espeak-ng and gtts-cli for voice feedback. - New VOICE_ENGINE config option with espeak-ng as the default. - Cleans up ~/.aletheia/ better. - Updated selection of themes. - Now prompts before exiting on the initial menu screen. - Ctrl-p now pauses all instances of Aletheia. - Volume fade between instances is more gradual. - Several other bug fixes.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -104,6 +104,7 @@ mkdir -p "$DESTDIR/share/man/man1/"
 mkdir -p "$DESTDIR/share/applications/"
 mkdir -p "$DESTDIR/share/aletheia/themes/"
 mkdir -p "$DESTDIR/share/aletheia/vimrc/"
+mkdir -p "$DESTDIR/share/aletheia/languages/"
 mkdir -p "$DESTDIR/share/icons/"
 
 if ! install -m 755 aletheia "$DESTDIR/bin/"; then
@@ -127,6 +128,9 @@ fi
 if ! install -m 644 ./vimrc/* "$DESTDIR/share/aletheia/vimrc/"; then
 	FAIL=true
 fi
+if ! install -m 644 ./languages/en "$DESTDIR/share/aletheia/languages/"; then
+	FAIL=true
+fi
 if ! install -m 644 example.config "$DESTDIR/share/aletheia/"; then
 	FAIL=true
 fi
@@ -141,6 +145,7 @@ FILES[4]="${DESTDIR}/share/icons/aletheia.png"
 FILES[5]="${DESTDIR}/share/aletheia/example.config"
 FILES+=("${DESTDIR}/share/aletheia/vimrc/"*)
 FILES+=("${DESTDIR}/share/aletheia/themes/"*)
+FILES+=("${DESTDIR}/share/aletheia/languages/"*)
 
 for i in $(seq 0 $((${#FILES[@]}-1))); do
 	chown "$USER:$USER" "${FILES[i]}"
@@ -160,7 +165,6 @@ if ! $FAIL; then
 	for i in $(seq 0 $((${#FILES[@]}-1))); do
 		path="${FILES[i]%/*}"
 		file="${FILES[i]##*/}"
-		#echo "${FILES[i]}"
 		echo -e "$NOCOLOR$path/$GREEN$file"
 	done
 
@@ -171,6 +175,6 @@ if ! $FAIL; then
 	fi
 	exit 0
 else
-	echo -e "${RED}failed$NOCOLOR"
+	echo -e "${RED}failed$NOCOLOR\n"
 	exit 1
 fi
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -43,6 +43,9 @@ fi
 if [ -d "$DESTDIR/share/aletheia/vimrc/" ]; then
 	FILES+=("${DESTDIR}/share/aletheia/vimrc/"*)
 fi
+if [ -d "$DESTDIR/share/aletheia/languages/" ]; then
+	FILES+=("${DESTDIR}/share/aletheia/languages/"*)
+fi
 
 FAIL=false
 for i in $(seq 0 $((${#FILES[@]}-1))); do
@@ -64,6 +67,12 @@ if [ -e "$DESTDIR/share/aletheia" ]; then
 	if [ -z "$(ls -1 "$DESTDIR/share/aletheia/vimrc")" ]; then
 		if ! rmdir "$DESTDIR/share/aletheia/vimrc" >/dev/null 2>/dev/null; then
 			echo -e "${RED}Failed:${NOCOLOR} Empty directory $DESTDIR/share/aletheia/vimrc/ not deleted."
+			FAIL=true
+		fi
+	fi
+	if [ -z "$(ls -1 "$DESTDIR/share/aletheia/languages")" ]; then
+		if ! rmdir "$DESTDIR/share/aletheia/languages" >/dev/null 2>/dev/null; then
+			echo -e "${RED}Failed:${NOCOLOR} Empty directory $DESTDIR/share/aletheia/languages/ not deleted."
 			FAIL=true
 		fi
 	fi
