- Added support for theme files and a collection of default themes. - Performance improvements. - Bug fixes in metadata caching algorithm. - Time now cached in addition to just metadata. - Everything passes shellcheck now. Thanks to Didier Spaier for the bug report. - 'f' and 'F' keys replaced by 'g' and 'G' in loop editor. - 'f' and 'F' keys now swap between locks. - 'x' now locks while 'X' unlocks the last lock. - Scale speed is now changed via 'C' now instead of 'X'. - New edit menu that can be accessed via 'O' that lets one edit lock file, loop file, queue, and config using VIM. - Loop mode's next and back buttons now iterate between loops before switching songs. - Loop editor's 'Z' function now allows for numeric input to export a file with x number of loops. Still experimental for now. - More robust menu especially in regards to smaller screens. - Improved error handling. - Progress bar now handles hours correctly. - In the queue, 'c' now swaps between filenames and tags. - Improved handling of special keys. Space now pauses. Tab adds files to the end of the playlist with a keyword. - Better handling of missing files. - Updated package scripts to install themes. - Install scripts now support --destdir in addition to the DESTDIR environment, with --destdir preferred when using sudo.
Enjoy!

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,12 +1,28 @@
 #!/bin/bash
 
 GREEN="\033[1;32m"
-BLUE="\033[1;36m"
 NOCOLOR="\033[0m"
 RED="\033[1;31m"
-YELLOW="\033[1;33m"
 
 DESTDIR=${DESTDIR:-/usr/local}
+if [ "$1" == "--destdir" ]; then
+	if [ -d "$2" ]; then
+		DESTDIR=$2
+	else
+		echo -ne "\n${RED}Error: Not a directory$NOCOLOR\n"
+		exit 1
+	fi
+fi
+
+if [ "${1:0:10}" == "--destdir=" ]; then
+	dir=${1:10}
+	if [ -d "$dir" ]; then
+		DESTDIR=$dir
+	else
+		echo -ne "\n${RED}Error: Not a directory$NOCOLOR\n"
+		exit 1
+	fi
+fi
 
 QUIT=false
 USER="$(whoami)"
@@ -54,13 +70,13 @@ fi
 echo -ne "\n${NOCOLOR}Installing... $NOCOLOR"
 
 DESTDIR=${DESTDIR%/}
+FAIL=false
 
 mkdir -p "$DESTDIR/bin/"
 mkdir -p "$DESTDIR/share/man/man1/"
-mkdir -p "$DESTDIR/share/applications"
-mkdir -p "$DESTDIR/share/icons"
-
-FAIL=false
+mkdir -p "$DESTDIR/share/applications/"
+mkdir -p "$DESTDIR/share/aletheia/themes/"
+mkdir -p "$DESTDIR/share/icons/"
 
 if ! install -m 755 aletheia "$DESTDIR/bin/"; then
 	FAIL=true
@@ -77,12 +93,18 @@ fi
 if ! install -m 644 aletheia.png "$DESTDIR/share/icons/"; then
 	FAIL=true
 fi
+if ! install -m 644 ./themes/* "$DESTDIR/share/aletheia/themes/"; then
+	FAIL=true
+fi
+
+sed -i "/^ALETHEIA_DATA_DIR/s#.*#ALETHEIA_DATA_DIR=\"${DESTDIR}/share/aletheia/\"#g" "$DESTDIR/bin/aletheia"
 
 FILES[0]="${DESTDIR}/bin/aletheia"
 FILES[1]="${DESTDIR}/bin/aletheia_desktop_launcher"
 FILES[2]="${DESTDIR}/share/man/man1/aletheia.1"
 FILES[3]="${DESTDIR}/share/applications/aletheia.desktop"
 FILES[4]="${DESTDIR}/share/icons/aletheia.png"
+FILES+=("${DESTDIR}/share/aletheia/themes/"*)
 
 for i in $(seq 0 $((${#FILES[@]}-1))); do
 	chown "$USER:$USER" "${FILES[i]}"
@@ -104,7 +126,7 @@ if ! $FAIL; then
 	done
 
 	if [ "$DESTDIR" != "/usr/local" ] && [ "$DESTDIR" != "/usr/local/" ]; then
-		echo -e "\n${NOCOLOR}Use ${GREEN}DESTDIR=${DESTDIR} ./uninstall$NOCOLOR to remove"
+		echo -e "\n${NOCOLOR}Use ${GREEN}./uninstall --destdir $DESTDIR$NOCOLOR to remove"
 	else
 		echo -e "\n${NOCOLOR}Use ${GREEN}./uninstall$NOCOLOR to remove"
 	fi
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -5,6 +5,24 @@ BLUE="\033[1;36m"
 NOCOLOR="\033[0m"
 
 DESTDIR=${DESTDIR:-/usr/local}
+if [ "$1" == "--destdir" ]; then
+	if [ -d "$2" ]; then
+		DESTDIR=$2
+	else
+		echo -ne "\n${RED}Error: Not a directory$NOCOLOR\n"
+		exit 1
+	fi
+fi
+
+if [ "${1:0:10}" == "--destdir=" ]; then
+	dir=${1:10}
+	if [ -d "$dir" ]; then
+		DESTDIR=$dir
+	else
+		echo -ne "\n${RED}Error: Not a directory$NOCOLOR\n"
+		exit 1
+	fi
+fi
 
 if [ ! -w "$DESTDIR" ]; then
 	echo -e "${RED}Error:$NOCOLOR Need root permission to uninstall from $DESTDIR"
@@ -16,16 +34,34 @@ FILES[1]="${DESTDIR}/bin/aletheia_desktop_launcher"
 FILES[2]="${DESTDIR}/share/man/man1/aletheia.1"
 FILES[3]="${DESTDIR}/share/applications/aletheia.desktop"
 FILES[4]="${DESTDIR}/share/icons/aletheia.png"
+if [ -d "$DESTDIR/share/aletheia/themes/" ]; then
+	FILES+=("${DESTDIR}/share/aletheia/themes/"*)
+fi
 
 FAIL=false
 for i in $(seq 0 $((${#FILES[@]}-1))); do
 	if ! rm -f "${FILES[i]}" >/dev/null 2>/dev/null; then
-		echo -e "${RED}Failed:${NOCOLOR} ${FILES[i]} not deleted." 
+		echo -e "${RED}Failed:${NOCOLOR} ${FILES[i]} not deleted."
 		FAIL=true
 	else
 		echo "rm -f \"${FILES[i]}\""
 	fi
 done
+
+if [ -e "$DESTDIR/share/aletheia" ]; then
+	if [ -z "$(ls -1 "$DESTDIR/share/aletheia/themes")" ]; then
+		if ! rmdir "$DESTDIR/share/aletheia/themes" >/dev/null 2>/dev/null; then
+			echo -e "${RED}Failed:${NOCOLOR} Empty directory $DESTDIR/share/aletheia/themes/ not deleted."
+			FAIL=true
+		fi
+	fi
+	if [ -z "$(ls -1 "$DESTDIR/share/aletheia")" ]; then
+		if ! rmdir "$DESTDIR/share/aletheia" >/dev/null 2>/dev/null; then
+			echo -e "${RED}Failed:${NOCOLOR} Empty directory $DESTDIR/share/aletheia/ not deleted."
+			FAIL=true
+		fi
+	fi
+fi
 
 if $FAIL; then
 	echo -e "${RED}Uninstall not successful$NOCOLOR"
